<?php
// Copyright (C) 2013 Medical Information Integration, LLC
// 
// The first level key is the displayed category name, and the second
// level is the line_id for the database.  Be careful not to duplicate
// these IDs!

$roslines = array(
	'CONSTITUTIONAL' => array(
		'CON001'  => xl('Weight Change'),
                'CON002'  => xl('Malaise/Fatigue'),
                'CON003'  => xl('Weakness'),
                'CON004'  => xl('Fever'),
                'CON005'  => xl('Chills'),
                'CON006'  => xl('Diaphoresis'),
                'CON007'  => xl('Other Comments/Observations')),
	'SKIN' => array(
		'SKIN001'  => xl('Rash'),
                'SKIN002'  => xl('Pruritus'),
                'SKIN003'  => xl('Hair Loss/Hirsutism'),
                'SKIN004'  => xl('Other Comments/Observations')),
    	'HENT' => array(
                'HENT001'  => xl('Headache'),
                'HENT002'  => xl('Hearing loss'),
                'HENT003'  => xl('Tinnitus'),
		'HENT004'  => xl('Ear pain'),
		'HENT005'  => xl('Ear Discharge'),
		'HENT006'  => xl('Epistaxis'),
		'HENT007'  => xl('Congestion'),
		'HENT008'  => xl('Sore throat'),
                'HENT009'  => xl('Odynophagia'),
                'HENT010'  => xl('Hoarseness'),
                'HENT011'  => xl('Neck stiffness'),
                'HENT012'  => xl('Other Comments/Observations')),
        'EYES' => array(
		'EYES001' => xl('Blurred vision'),
                'EYES002' => xl('Diplopia'),
                'EYES003' => xl('Scotoma'),
                'EYES004' => xl('Photophobia'),
                'EYES005' => xl('Eye pain'),
                'EYES006' => xl('Eye Discharge'),
                'EYES007' => xl('Eye Redness'),
                'EYES008' => xl('Other Comments/Observations')),            
    	'CARDIOVASCULAR' => array(
		'CARDIO001' => xl('Chest pain'),
                'CARDIO002' => xl('Palpitations'),
                'CARDIO003' => xl('Orthopnea'),
                'CARDIO004' => xl('Paroxysmal Nocturnal Dyspnea'),
                'CARDIO005' => xl('Edema'),
                'CARDIO006' => xl('Claudication'),
                'CARDIO007' => xl('Other Comments/Observations')),
        'RESPIRATORY' => array(
		'RESPT001' => xl('Cough'),
                'RESPT002' => xl('Hemoptysis'),
                'RESPT003' => xl('Sputum Production'),
                'RESPT004' => xl('Dyspnea'),
                'RESPT005' => xl('Wheezing'),
                'RESPT006' => xl('Pleuritic Pain'),
                'RESPT007' => xl('Other Comments/Observations')),
        'GASTROINTESTINAL' => array(
		'ABDMN001' => xl('Nausea'),
                'ABDMN002' => xl('Vomiting'),
                'ABDMN003' => xl('Anorexia'),
                'ABDMN004' => xl('Dysphagia'),
                'ABDMN005' => xl('Hematochezia'),
                'ABDMN006' => xl('Hematemesis'),
                'ABDMN007' => xl('Melena'),
                'ABDMN008' => xl('Dyspepsia'),
                'ABDMN009' => xl('Abdominal Pain'),
                'ABDMN010' => xl('Jaundice'),
                'ABDMN011' => xl('Diarrhea'),
                'ABDMN012' => xl('Constipation'),
                'ABDMN013' => xl('Rectal Pain'),
                'ABDMN014' => xl('Other Comments/Observations')),
            'GENITOURINARY' => array(
		'GEN001' => xl('Nocturia'),
                'GEN002' => xl('Frequency'),
                'GEN003' => xl('Dysuria'),
                'GEN004' => xl('Flank Pain'),
                'GEN005' => xl('Hematuria'),
                'GEN006' => xl('Urgency'),
                'GEN007' => xl('Stranguria'),
                'GEN008' => xl('Incomplete Voiding'),
                'GEN009' => xl('Incontinence'),
                'GEN010' => xl('Other Comments/Observations')),
    	'MUSCULOSKELETAL' => array(
		'MUSC001' => xl('Myalgias'),
                'MUSC002' => xl('Joint Pain'),
                'MUSC003' => xl('Neck pain'),
                'MUSC004' => xl('Back pain'),
                'MUSC005' => xl('Other Comments/Observations')),
    	'ENDOCRINE' => array(
		'ENDO001' => xl('Heat/Cold intolerance'),
                'ENDO002' => xl('Polydipsia'),
                'ENDO003' => xl('Polyphagia'),
                'ENDO004' => xl('Other Comments/Observations')),
        'HEMAT/MYMPH' => array(
		'HEMY001' => xl('Lymphadenopathy'),
                'HEMY002' => xl('Easy bruise/bleed'),
                'HEMY003' => xl('Frequent infections'),
                'HEMY004' => xl('Other Comments/Observations')),
	'NEUROLOGICAL' => array(
		'NEURO001' => xl('Vertigo/Dizziness'),
                'NEURO002' => xl('Tremor'),
                'NEURO003' => xl('Muscle Weakness'),
		'NEURO004' => xl('Syncope'),
		'NEURO005' => xl('Seizures'),
		'NEURO006' => xl('Parasthesia'),
		'NEURO007' => xl('Gait Disturbance'),
                'NEURO008' => xl('Other Comments/Observations')),
	'OTHER' => array(
		'OTHER001' => xl('Additional Comments'))
);
?>
